name: Tailscale RDP Access

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: windows-latest
    steps:

      - name: Install Tailscale & Bring Up
        shell: powershell
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          # نصب Chocolatey در صورت نیاز
          if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            iex ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }

          # نصب Tailscale
          choco install tailscale --no-progress --yes

          # بارگذاری ماژول Chocolatey برای دسترسی به refreshenv
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

          # ریفرش کردن محیط تا PATH جدید شناسایی شود
          refreshenv

          # بالا آوردن Tailscale
          tailscale up --authkey $env:TAILSCALE_AUTHKEY --hostname github-runner

      - name: Set RDP user and password
        shell: powershell
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          net user runneradmin $env:RDP_PASSWORD /add
          net localgroup administrators runneradmin /add

      - name: Print Tailscale IP
        shell: powershell
        run: |
          tailscale ip
