name: Tailscale RDP Access

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: windows-latest
    steps:
      - name: Download Tailscale standalone
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-ipn.exe" -OutFile "tailscale.exe"

      - name: Start Tailscale (login)
        run: |
          .\tailscale.exe up --authkey tskey-auth-kPqBbVk2Ru11CNTRL-1finLB8HTU4uDSAgsGbYU4hTS58Yfr2p3 --hostname github-runner

      - name: Set RDP password
        run: net user runneradmin MyStrongPassword123!

      - name: Print Tailscale IP
        run: .\tailscale.exe ip
