name: Tailscale RDP Access

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: windows-latest
    steps:
      - name: Install Chocolatey (if missing)
        shell: powershell
        run: |
          if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }

      - name: Install Tailscale via Chocolatey
        shell: powershell
        run: |
          choco install tailscale --no-progress --yes

      - name: Bring up Tailscale (full path)
        shell: powershell
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          & "C:\Program Files (x86)\Tailscale\tailscale.exe" up --authkey $env:TAILSCALE_AUTHKEY --hostname github-runner

      - name: Set RDP user and password
        shell: powershell
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          net user runneradmin $env:RDP_PASSWORD /add
          net localgroup administrators runneradmin /add

      - name: Print Tailscale IP
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Tailscale\tailscale.exe" ip
