# .github/workflows/tailscale-rdp.yml
name: Tailscale RDP Access

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: windows-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      RDP_PASSWORD:    ${{ secrets.RDP_PASSWORD }}

    steps:
      - name: Install Chocolatey (if missing)
        shell: powershell
        run: |
          if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            iex ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }

      - name: Install Tailscale via Chocolatey
        shell: powershell
        run: |
          choco install tailscale --no-progress --yes

      - name: Start Tailscale (direct shim path)
        shell: powershell
        run: |
          $exe = 'C:\ProgramData\chocolatey\bin\tailscale.exe'
          Write-Host "Launching Tailscale from $exe"
          & $exe up --authkey $env:TAILSCALE_AUTHKEY --hostname github-runner

      - name: Create (or update) RDP user
        shell: powershell
        run: |
          # رمز عبور رو امن می‌کنیم
          $pw = ConvertTo-SecureString $env:RDP_PASSWORD -AsPlainText -Force
          if (-not (Get-LocalUser runneradmin -ErrorAction SilentlyContinue)) {
            New-LocalUser runneradmin -Password $pw -PasswordNeverExpires -AccountNeverExpires
          } else {
            Set-LocalUser runneradmin -Password $pw
          }
          Add-LocalGroupMember Administrators runneradmin -ErrorAction SilentlyContinue

      - name: Print Tailscale IP
        shell: powershell
        run: |
          $exe = 'C:\ProgramData\chocolatey\bin\tailscale.exe'
          & $exe ip
