name: Tailscale RDP Access (Guaranteed to Work)
on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: windows-latest
    steps:
      - name: Install Tailscale via Chocolatey
        run: choco install tailscale -y --no-progress

      - name: Add Tailscale installation folder to the PATH
        run: echo "C:\Program Files\Tailscale" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Start Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-runner

      - name: Enable RDP and Set User Password
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        shell: powershell
        run: |
          # Set the password for the existing 'runneradmin' user
          $password = ConvertTo-SecureString -String $env:RDP_PASSWORD -AsPlainText -Force
          Set-LocalUser -Name runneradmin -Password $password
          
          # Enable Remote Desktop connections
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Show IP and Keep Alive
        run: |
          echo "✅ RDP is ready!"
          echo "Your Tailscale IP Address is:"
          tailscale ip -4
          echo "This connection will remain active for 6 hours."
          Start-Sleep -Seconds 21000
